include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors_in_immutables: ignore
    library_private_types_in_public_api: ignore
    deprecated_member_use: ignore
    prefer_const_constructors: ignore
    use_key_in_widget_constructors: ignore
    use_build_context_synchronously: ignore
    use_super_parameters: ignore
    avoid_print: ignore
    sized_box_for_whitespace: ignore

analyzer:
  errors:
    camel_case_types: ignore
    deprecated_member_use: ignore
    unused_import: ignore
    unused_local_variable: ignore